export const Sign_in = "signin"
export const Sign_out = "signout"
export const Profile = "profile"
export const Refresh = "refresh"
export const EventDetailAdd = "EventDetailAdd"
export const EventDetailRem = "EventDetailRem"